//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineAssessmentSet
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssessmentSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AssessmentSet()
        {
            this.Questions = new HashSet<Question>();
            this.AssessmentSet_Detail = new HashSet<AssessmentSet_Detail>();
        }
    
        public int assessId { get; set; }
        public string assessName { get; set; }
        public Nullable<System.TimeSpan> timeLimit { get; set; }
        public Nullable<int> allowAttempt { get; set; }
        public Nullable<System.DateTime> dateCreated { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Question> Questions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssessmentSet_Detail> AssessmentSet_Detail { get; set; }
    }
}
