//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineAssessmentSet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lecturer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lecturer()
        {
            this.AssessmentSet_Detail = new HashSet<AssessmentSet_Detail>();
        }
    
        public int lecId { get; set; }
        public string lecLastName { get; set; }
        public string lecFirstName { get; set; }
        public Nullable<int> lecIc { get; set; }
        public string lecEmail { get; set; }
        public Nullable<int> lecContactNo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssessmentSet_Detail> AssessmentSet_Detail { get; set; }
    }
}
