//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineAssessmentSet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int studId { get; set; }
        public string studLastName { get; set; }
        public string studFirstName { get; set; }
        public Nullable<int> studIc { get; set; }
        public string studEmail { get; set; }
        public Nullable<int> studContactNo { get; set; }
        public Nullable<System.DateTime> studYearIntake { get; set; }
    
        public virtual AssessmentSet_Detail AssessmentSet_Detail { get; set; }
    }
}
